---
title: "Project Two"
author: "Justice Wilkins"
date: "3/8/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
require(mlbench)
# load the data set
data(BreastCancer)
# some algorithms don't like missing values, so remove rows with missing values
BreastCancer <- na.omit(BreastCancer) 
# remove the unique identifier, which is useless and would confuse the machine learning algorithms
BreastCancer$Id <- NULL 

```


```{r}
library(e1071)
mysvm <- svm(Marg.adhesion ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Marg.adhesion)
```

```{r}
library(klaR)
mynb <- NaiveBayes(Marg.adhesion ~ ., BreastCancer)
mynb.pred <- predict(mynb,BreastCancer)
table(mynb.pred$class,BreastCancer$Marg.adhesion)

```

```{r}
library(MASS)
#Decision trees
library(rpart)
mytree <- rpart(Marg.adhesion ~ ., BreastCancer)
#plot(mytree); text(mytree) # in "BreastCancer_tree.ps"
#summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Marg.adhesion)
```



```{r}
#Regularised Discriminant Analysis
library(klaR)
myrda <- rda(Marg.adhesion ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Marg.adhesion)

as.data.frame(myrda.pred$class)
              

```

```{r}
#Random Forests
library(randomForest)
myrf <- randomForest(Marg.adhesion ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Marg.adhesion)
```


```{r}
#Create Column Names For Classifcation Models
Naiyes.m <- mynb.pred$class
SVM.m <- mysvm.pred
DTree.m <- mytree.pred
RDA.m <- myrda.pred$class
rf.m <- myrf.pred

#Create data frame - Make sure to transpose rows and columns, and create as a data frame with the classifcations
Class.df <- t(as.data.frame(rbind(Naiyes.m, SVM.m, DTree.m, RDA.m, rf.m)))


#Select number with highest frequenct (MODE of all classications)
Class.Mode <- apply(Class.df, 1, function(idx) which.max(tabulate(idx)))

#Insert Class Frequency (Mode) into the classifcation model data frame
Freq.df <- t(as.data.frame(rbind(mynb.pred$class, mysvm.pred, mytree.pred, myrda.pred$class, myrf.pred, Class.Mode)))
```


